Add SSH key check and update deployment process

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -6,7 +6,29 @@ on:
       - master
 
 jobs:
+  check-keys:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check if SSH keys exist
+      run: |
+        if [ -z "${{ secrets.HOST }}" ]; then
+          echo "Error: HOST is missing in GitHub Secrets."
+          exit 1
+        fi
+
+        if [ -z "${{ secrets.USERNAME }}" ]; then
+          echo "Error: USERNAME is missing in GitHub Secrets."
+          exit 1
+        fi
+
+        if [ -z "${{ secrets.SSH_KEY }}" ]; then
+          echo "Error: SSH_KEY is missing in GitHub Secrets."
+          exit 1
+        fi
+
   deploy:
+    needs: check-keys
     runs-on: ubuntu-latest
 
     steps:
@@ -27,22 +49,11 @@ jobs:
         sed -e "s/HIDDEN_TOKEN/$HIDDEN_TOKEN/g" src/environments/environment.prod.ts.template > src/environments/environment.prod.ts
         ng b --configuration production
 
-    - name: Debug
-      run: |
-        ls -R $GITHUB_WORKSPACE/dist/cineba
-
     - name: Create a version file with the commit hash and tag
       run: |
         echo $GITHUB_SHA > dist/cineba/version.txt
         echo $GITHUB_REF >> dist/cineba/version.txt
 
-    - name: Copy files to server
-      uses: appleboy/ssh-action@master
-      with:
-        host: ${{ secrets.HOST }}
-        username: ${{ secrets.USERNAME }}
-        key: ${{ secrets.SSH_KEY }}
-        script: |
-          cd /home/bitnami/cineba-api/wwwroot
-          scp -r $GITHUB_WORKSPACE/dist/cineba/* .
-          pm2 restart serve
+    - name: Copy files to server using scp
+      run: |
+        scp -r -i ${{ secrets.SSH_KEY }} dist/cineba/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/cineba-api/wwwroot
